### PR TITLE
Retry for 502-504 codes, fail on >= 400 codes

### LINKED ISSUE #72: Undefined error when nextUri request returns non-200 status code
We hit the following error in production:

```
TypeError: Cannot read properties of undefined (reading 'state')
    at /app/foo/node_modules/presto-client/lib/presto-client/index.js:338:70
    at IncomingMessage.<anonymous> (/app/foo/node_modules/presto-client/lib/presto-client/index.js:133:13)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

From debugging, it seems that the trino server we were querying against returned a `50x` response (our logging did not capture this) on the request in `fetch_next` function, and so `typeof response === 'string'` and so `response.stats === undefined` in the callback.

Looking at the [presto docs](https://prestodb.io/docs/current/develop/client-protocol.html), it documents that a `503` error should trigger a retry while the [trino docs](https://trino.io/docs/current/develop/client-protocol.html) says that a `502`, `503`, or `504` should trigger a retry. Anything beyond those and `200` should be considered an error case.

My proposed change would be that for both the initial request and all subsequent requests against `nextUri`, if they return `200`, then handle it as right now. If it returns `[502, 503, 504]`, then do a retry after 50-100ms. If the request returns something outside of those codes, then return an error with some generic message.

For the 50x case, will probably want to add some way to timeout querying so that if the server never responds, the query doesn't just permanently hang.

### PR DESCRIPTION
**Pull request by MasterOdin**
Closes #72 

PR modifies the behavior of the client such that:
* If the response returns a `502`, `503`, or `504` code, then the request will be retried after 50-100ms
* If the response returns with >= 400 code that does not match above, then throw an error

and that this happens consistently whether the codes happen on the first request or a subsequent request. Previously, all of these codes would throw an error only on the first request, while all subsequent requests would trigger an uncaught exception.

I included tests that validate the proper behavior for triggering these codes on the first `POST` call to `/v1/statement` as well as the subsequent `GET` call to `/v1/statement/...`.

### CODE REVIEW

**Comment by tagomoris** [comment]
I have some requests for the change:

* a new callback `retry` (or something else) to be called when the request is retried, to notify users about retries (and server side errors)
* a new parameter `timeout` to stop retries and call `error` callback, with a default value (1 minutes or so), to not make queries which never stops
* update test case names to describe what is tested (what should be verified), instead of what the test code does

**Comment by MasterOdin** [comment]
To address the above comments, namely (1), I ended up having to rewrite some amount of `statementResource` method so that we could have a single function that wraps making requests so that I could put the retry logic in one place as any request could fail. I think I've retained backwards compatibility in terms of error message format on first request vs 2+ request, as well as only allowing cancelling on the 2+ request.

> a new parameter timeout to stop retries and call error callback, with a default value (1 minutes or so), to not make queries which never stops

In terms of backwards compatibility, I think this shouldn't have a default?

> update test case names to describe what is tested (what should be verified), instead of what the test code does

I renamed the test, but if you'd like to see a different name, I'd prefer you give me more exact naming instead of guessing. Here's the current test output:
```
  ✓ cannot use basic and custom auth (12 ms)
  presto
    ✓ simple query (3219 ms)
    ✓ query with error (1675 ms)
  trino
    ✓ simple query (3293 ms)
    ✓ query with error (1645 ms)
  when server returns non-200 response
    the client should retry for 50x code
      the client retries for 502 code
        ✓ the client returns success (992 ms)
      the client retries for 503 code
        ✓ the client returns success (962 ms)
      the client retries for 504 code
        ✓ the client returns success (1001 ms)
    the client fails for 404 code
      the client fails after 0 requests
        ✓ the client returns error (4 ms)
      the client fails after 1 requests
        ✓ the client returns error (817 ms)
    the client fails for 500 code
      the client fails after 0 requests
        ✓ the client returns error (12 ms)
      the client fails after 1 requests
        ✓ the client returns error (824 ms)
  when timeout is set
    ✓ the query times out (1009 ms)
```

**Comment by tagomoris** [comment]
> In terms of backwards compatibility, I think this shouldn't have a default?

From a compatibility viewpoint, this change is incompatible because it retries requests for 50x errors. If we want to keep the behavior about errors, we should introduce a parameter like `retry_temporary_errors` with default `false` to not retry. (I don't want to do so.)

This change introduces a kind of incompatibility, but we should keep the behavior consistent. In previous versions, users' queries will stop when they meet errors (after a fixed amount of time). With error retries without default valued `timeout`, queries will never stop forever if a query causes 50x error always. That's an inconsistent behavior users don't expect.

So, when we introduce retries, we should ensure that queries will finish after a period of time anyway.
Does it explain the reason enough?

**Comment by MasterOdin** [comment]
Fair enough @tagomoris. Per your feedback, I've made the timeout default to 60 seconds, with the ability to disable it by setting the field to `null` or `0`. The timeout can be set both at the client level as well as the query level.

File: lib/presto-client/index.js [hunk 1]
```diff
@@ -220,167 +229,212 @@ Client.prototype.statementResource = function(opts) {
...
+                if (first_request) {
+                    var message = "execution error" + (response && response.length > 0 ? ":" + response : "");
+                    if (response && response.error && response.error.message)
+                        message = response.error.message;
+                    error_callback({message, error: (error || response.error), code});
+                } else {
                     error_callback(error || response.error);
-                    return;
                 }
+                clear_timeout();
```
Comment (tagomoris) [inline lib/presto-client/index.js:371]: Clearing timeout should be earlier.

File: lib/presto-client/index.js [hunk 2]
```diff
@@ -220,167 +229,212 @@ Client.prototype.statementResource = function(opts) {
...
+            if (first_request && (!response.id || !response.nextUri || !response.infoUri)) {
+                var error_message = null;
+                if (!response.id)
+                    error_message = "query id missing in response for POST /v1/statement";
+                else if (!response.nextUri)
+                    error_message = "nextUri missing in response for POST /v1/statement";
+                else if (!response.infoUri)
+                    error_message = "infoUri missing in response for POST /v1/statement";
+                error_callback({message: error_message, data: response});
+                clear_timeout();
```
Comment (tagomoris) [inline lib/presto-client/index.js:384]: ditto.

File: lib/presto-client/index.js [hunk 3]
```diff
@@ -220,167 +229,212 @@ Client.prototype.statementResource = function(opts) {
...
             }
-            client.request(next_uri, function(error, code, response){
-                if (error || response.error) {
+
+            if (error || (response && response.error)) {
+                if (first_request) {
+                    var message = "execution error" + (response && response.length > 0 ? ":" + response : "");
+                    if (response && response.error && response.error.message)
+                        message = response.error.message;
+                    error_callback({message, error: (error || response.error), code});
```
Comment (tagomoris) [inline lib/presto-client/index.js:367]: The error callback argument is modified to an incompatible form(?) only when it's the first request. What's the reason?

File: lib/presto-client/index.js [hunk 4]
```diff
@@ -220,167 +229,212 @@ Client.prototype.statementResource = function(opts) {
...
                 }
+                clear_timeout();
+                return;
+            }
 
-                if (state_callback && (last_state !== response.stats.state || enable_verbose_state_callback)) {
-                    state_callback(null, response.id, response.stats);
-                    last_state = response.stats.state;
-                }
+            if (first_request && (!response.id || !response.nextUri || !response.infoUri)) {
```
Comment (tagomoris) [inline lib/presto-client/index.js:375]: Could you explain why this is checked only when it's the first request?

File: lib/presto-client/index.js [hunk 5]
```diff
@@ -124,13 +126,18 @@ Client.prototype.request = function(opts, callback) {
...
+                try {
+                    data = parser.parse(data);
+                    error = null;
+                }
                 catch (x) {
                     /* ignore json parse error (and don't parse) for non-json content body */
                 }
             }
-            callback(null, response_code, data);
+            callback(error, response_code, data);
```
[the remark this answers is not in the document]
Comment (MasterOdin) [reply lib/presto-client/index.js:146]: Modified in 4f0a9aafad7b64b25d90bfa59f9777df5bd50bf7, now only `200` errors will return the "could not parse response" error message, while other status codes will just log the status code out instead.

I've also added a test for this.

File: lib/presto-client/index.js [hunk 6]
```diff
@@ -220,167 +229,212 @@ Client.prototype.statementResource = function(opts) {
     var state_callback = opts.state;
     var columns_callback = opts.columns;
     var data_callback = opts.data;
+    var retry_callback = opts.retry;
     var success_callback = opts.success || opts.callback;
     var error_callback = opts.error || opts.callback;
 
     var enable_verbose_state_callback = this.enableVerboseStateCallback || false;
+    var current_req;
```
[the remark this answers is not in the document]
Comment (MasterOdin) [reply lib/presto-client/index.js]: Nope, modified in 4f0a9aafad7b64b25d90bfa59f9777df5bd50bf7 to default to `null`, though having it be `undefined` or `null` makes no overall difference.

File: lib/presto-client/index.js [hunk 7]
```diff
@@ -220,167 +229,212 @@ Client.prototype.statementResource = function(opts) {
...
+    var last_state = null;
+    var query_id = null;
+    var timed_out = false;
+
+    var timeout_value = typeof opts.timeout !== 'undefined' ? opts.timeout : this.timeout;
```
[the remark this answers is not in the document]
Comment (MasterOdin) [reply lib/presto-client/index.js]: Done in 4f0a9aafad7b64b25d90bfa59f9777df5bd50bf7.

File: lib/presto-client/index.js [hunk 8]
```diff
@@ -220,167 +229,212 @@ Client.prototype.statementResource = function(opts) {
...
+                "state": "FINISHED",
+            },
+            "columns": [ { "type": "bigint", "name": "cnt" } ],
+            "infoUri": "http://localhost:8080/v1/query/20140120_032523_00000_32v8g",
+            "id": "20140120_032523_00000_32v8g"
+        }
+    */
+
+    var first_request = true;
+    var fetch_next = function(next_uri){
```
[the remark this answers is not in the document]
Comment (MasterOdin) [reply lib/presto-client/index.js]: Renamed to be simply `fetch` in 1145e5c7aa5320f27d4929ea2ca0773d8b6c94dc. Let me know if that's fine?

File: lib/presto-client/index.js [hunk 9]
```diff
@@ -220,167 +229,212 @@ Client.prototype.statementResource = function(opts) {
...
-                        error_callback({message: "query fetch canceled, but Presto query cancel may fail", error: error, code: code});
-                    } else {
-                        error_callback({message: "query fetch canceled by operation"});
-                    }
-                });
+        current_req = client.request(next_uri, function(error, code, response){
+            // same as above, we have already timed out and shown an error, so abort out
+            if (timed_out) {
+                return;
+            } else if ([502, 503, 504].includes(code)) {
```
[the remark this answers is not in the document]
Comment (MasterOdin) [reply lib/presto-client/index.js]: Done in 4f0a9aafad7b64b25d90bfa59f9777df5bd50bf7.

File: lib/presto-client/index.js [hunk 10]
```diff
@@ -220,167 +229,212 @@ Client.prototype.statementResource = function(opts) {
...
+                setTimeout(function(){
+                    fetch_next(next_uri);
+                }, Math.floor(Math.random() * 51) + 50);
```
[the remark this answers is not in the document]
Comment (MasterOdin) [reply lib/presto-client/index.js]: Done in 4f0a9aafad7b64b25d90bfa59f9777df5bd50bf7

File: lib/presto-client/index.js (hunk 1 above)
Comment (MasterOdin) [reply lib/presto-client/index.js]: Move it up in 4f0a9aafad7b64b25d90bfa59f9777df5bd50bf7.

File: lib/presto-client/index.js (hunk 2 above)
Comment (MasterOdin) [reply lib/presto-client/index.js]: Move it up in 4f0a9aafad7b64b25d90bfa59f9777df5bd50bf7.

File: lib/presto-client/index.js (hunk 3 above)
Comment (MasterOdin) [reply lib/presto-client/index.js:374]: This is combining the original logic of:
https://github.com/tagomoris/presto-client-node/blob/84f76d981482c5dd710a147ebfe89efa1731d85f/lib/presto-client/index.js#L230-L238

and

https://github.com/tagomoris/presto-client-node/blob/84f76d981482c5dd710a147ebfe89efa1731d85f/lib/presto-client/index.js#L333-L336

into a single function call, where the former was only done on the first POST request, while the latter was done for all subsequent GET requests.

File: lib/presto-client/index.js (hunk 4 above)
Comment (MasterOdin) [reply lib/presto-client/index.js:381]: Similar to above, this block is replicating this from master:

https://github.com/tagomoris/presto-client-node/blob/84f76d981482c5dd710a147ebfe89efa1731d85f/lib/presto-client/index.js#L260-L270

where this only gets run on that first POST request, and then all subsequent GET requests do not have it. If you wanted me to apply this to all requests, then could only reasonably check for `response.id` for existing, as I think per the REST API docs, the `nextUri` could be undefined on the final GET payload, while `infoUri` is not mentioned so I'm not sure about that.

File: lib/presto-client/index.js [hunk 11]
```diff
@@ -220,167 +235,212 @@ Client.prototype.statementResource = function(opts) {
...
+            if (data_callback && response.data) {
+                data_callback(null, response.data, response.columns, response.stats);
+            }
+
+            if (response.nextUri) {
+                fetchNextWithTimeout(response.nextUri, client.checkInterval);
+                return;
+            }
+
+            clear_timeout();
```
Comment (MasterOdin) [inline lib/presto-client/index.js:431]: Should this be moved up? Right now the docs say that the timeout is counted until the first row of results have come back.

I wonder if it'd be better to have a set timeout until the first results come back, and then have a separate "retry counter" that each 50x error can happen Y times before we abandon the query.

**Comment by Nurymka** [comment]
any updates on this PR? would be really handy if we can get this merged

**Comment by tagomoris** [comment]
Ah, I missed the updates in Aug. I'll check it in this week.

File: lib/presto-client/index.js [hunk 12]
```diff
@@ -220,167 +235,212 @@ Client.prototype.statementResource = function(opts) {
...
-                }
+            first_request = false;
 
-                if (data_callback && response.data) {
-                    data_callback(null, response.data, response.columns, response.stats);
-                }
+            if (state_callback && (last_state !== response.stats.state || enable_verbose_state_callback)) {
+                state_callback(null, response.id, response.stats);
+                last_state = response.stats.state;
+                query_id = response.id;
```
Comment (tagomoris) [inline lib/presto-client/index.js:399]: I'm sorry that I missed this at the last review, but should this be out of the `if (state_callback &&...)`?
`query_id` should be set even when `state_callback` is not set.

**Comment by tagomoris** [comment]
The change looks good to me except for `query_id`.

File: lib/presto-client/index.js (hunk 12 above)
Comment (MasterOdin) [reply lib/presto-client/index.js]: Done in 43a555b26eca3f977f44b1ce9600896bc69c1bd0. I added a `|| query.id` in the off chance that the response does not contain an `id`, we don't lose the previously set one, though the value should be stable over the lifetime of the request.

File: lib/presto-client/index.js [hunk 13]
```diff
@@ -220,167 +229,212 @@ Client.prototype.statementResource = function(opts) {
...
-            error_callback({message: error_message, data: data});
+        else if (!first_request && cancel_checker && cancel_checker()) {
+            client.request({ method: 'DELETE', path: next_uri }, function(error, code, data){
+                if (error || code !== 204) {
+                    error_callback({message: "query fetch canceled, but Presto query cancel may fail", error: error, code: code});
+                } else {
+                    error_callback({message: "query fetch canceled by operation"});
+                }
+            });
+            clear_timeout();
```
[the remark this answers is not in the document]
Comment (MasterOdin) [reply lib/presto-client/index.js]: Done in 4f0a9aafad7b64b25d90bfa59f9777df5bd50bf7

**Comment by tagomoris** [comment]
I want this to be rebased on the change of #78...

**Comment by tagomoris** [comment]
@MasterOdin Could you rebase on the current master?

**Comment by MasterOdin** [comment]
@tagomoris rebased on the latest `master`. I also condensed the commits down to once since I'm already doing history rewriting on the branch.

**Comment by tagomoris** [comment]
Merged. Thank you!
